version: "3.8"
services:
  postgres:
    container_name: dev-progress-postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=shyss
      - POSTGRES_DB=dev-progress
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
